spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gamelist
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



  jackson:
    default-property-inclusion: non_null

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com


server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

